// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKis6RGtHJwsSWVRhl6b7f1F5wQQazHxM',
    appId: '1:260823137789:web:1766cf9d56a65c954ced94',
    messagingSenderId: '260823137789',
    projectId: 'drop-lock-app',
    authDomain: 'drop-lock-app.firebaseapp.com',
    databaseURL: 'https://drop-lock-app-default-rtdb.firebaseio.com',
    storageBucket: 'drop-lock-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOE9Hghj9R9mOOoUiFo4klBeqnfwB3pR4',
    appId: '1:260823137789:android:65cd9c4647c336814ced94',
    messagingSenderId: '260823137789',
    projectId: 'drop-lock-app',
    databaseURL: 'https://drop-lock-app-default-rtdb.firebaseio.com',
    storageBucket: 'drop-lock-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxNRZZiPGGY-OKKDHWQUky5FQ86wtmFo',
    appId: '1:260823137789:ios:e2f30b635a9c99044ced94',
    messagingSenderId: '260823137789',
    projectId: 'drop-lock-app',
    storageBucket: 'drop-lock-app.firebasestorage.app',
    iosBundleId: 'com.example.appnew',
  );
}